### ISSUE TITLE
Windows: no markers shown in map

### ISSUE THREAD

**Issue by vvim** [vvim/routetool#49]
(mail van 2017 - 11 - 22 "routetool")

Sinds gisteren krijg ik niks meer te zien op de google maps kaart (geen ballonnetjes met inzamelpunten en geen route).

Wat is er gebeurd?

De routeberekening en aanmaak van vervoerslijst werkt wel nog, maar je krijgt dus niks meer te zien op de kaart.
ik krijg wel de kaart te zien, maar niet de markers.

Het probleem deed zich eerst voor op mijn laptop. Dan heb ik onze vaste computer geprobeerd en daar was het hetzelfde.

**Comment by vvim** [comment]
* problem occurs on Windows system, not in Linux
* HTML is correct and when opened in a browser, will show the markers, but QWebView (in Windows) refuses

The markers were already buggy on Windows machines, maybe the problem is with the computer that I use for building routetool?  Maybe I need to freshly install Qt and re-compile the routetool from a fresh Windows-machine? (see also https://github.com/vvim/BT_deelnemers )


**Possible solutions:**
  1. problem with the windows-laptop that I use for building routetool for Windows?
      -> Maybe I need to freshly install Qt and re-compile the routetool from a fresh Windows-machine?

  2. make very simple dummy project in newest version of Qt and test QWebView with Google Maps behaviour for improvement?
      -> help through StackOverflow?

  3. research "QWebview markers Google Maps", p.e. http://www.qtcentre.org/threads/36640-QWebView-Problem-Drag-amp-Drop-Markers-in-Google-Maps

**Current bugfix:** write HTML to a separate file, and ask the user to open the HTML-file

**Comment by ghost** [comment]
Je hebt een Google API key nodig...

-----Oorspronkelijk bericht-----
Van: Wim Deprez [mailto:notifications@github.com] 
Verzonden: donderdag 23 november 2017 14:18
Aan: vvim/routetool <routetool@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [vvim/routetool] Windows: no markers shown in map (#49)

(mail van 2017 - 11 - 22 "routetool")

Sinds gisteren krijg ik niks meer te zien op de google maps kaart (geen ballonnetjes met inzamelpunten en geen route).

Wat is er gebeurd?

De routeberekening en aanmaak van vervoerslijst werkt wel nog, maar je krijgt dus niks meer te zien op de kaart.
ik krijg wel de kaart te zien, maar niet de markers.

Het probleem deed zich eerst voor op mijn laptop. Dan heb ik onze vaste computer geprobeerd en daar was het hetzelfde.

**Comment by vvim** [comment]
@MHermsen hartelijk dank voor je reactie, ik ben hier zeer blij om.

We gebruiken momenteel al een Google API key, dus ik vrees dat dat het probleem niet is. Hieronder een voorbeeld van onze HTML-code. Werkt perfect in een standaard webbrowser en in een QWebView op mijn Linux-laptop, maar weigert dus dienst in een QWebView op mijn Windows-laptop:
[html-google-maps-test-20171123.txt](https://github.com/vvim/routetool/files/1499367/html-google-maps-test-20171123.txt)

in bovenstaande html heb ik onze API-key vervangen door de tekst "_VulHierApiKeyIn_"

**Comment by ghost** [comment]
Ik vermoedde eerst een UTF8 probleem maar dat is het niet.... bij nader bestuderen van je code lijkt het erop dat hoe je de stops in de variabele stopt een probleem zou kunnen zijn tussen Linux en Windows !

Ik moet namelijk Google soms ook vertellen welke taal te gebruiken ?  browserlanguage kan ook een ramp zijn weet ik uit ervaring....    Waarschijnlijk ben ik je project ooit gaan volgen en reageer ik nu spontaan.... maar als dit de manier is van een route berekenen doe ik namelijk iets anders !

**Comment by vvim** [comment]
@MHermsen ik was inderdaad (aangenaam) verrast met je input, ik gebruik deze "issues" als geheugensteuntjes voor mezelf en had geen idee dat iemand ooit zou meelezen :-) Maar ben dus zeker blij met je opmerking.

Als spreekt over browserlanguage, bedoel je dat ik in mijn HTML beter moet specifiëren dat het om JavaScript gaat?

.

Dus
      `      <script type="text/javascript">`
ipv
      `      <script>`

?

.

---

notitie voor @vvim , zie:

- https://stackoverflow.com/questions/314158/google-maps-geocoding-always-uses-browser-language/314312#314312

- https://developers.google.com/maps/documentation/javascript/localization

**Comment by ghost** [comment]
Nee dat bedoelde ik niet...ik bedoel clients browsers.... Aangezien ik Internationaal werk weet ik dat de browserlanguage van de client een spelbreker kan zijn in de software... vandaar dat ik Google dus in een bepaalde taal duw.   Ik heb dit bv in Nederland ook gehad... een Nederlander heeft vaak wel NL als taal maar een Engelse persoon heeft zijn browserlanguage op Engels staan en dan krijg je andere gegevens terug van Google ????  Of Google kan het niet vinden omdat die eerst ergens anders zoekt !!!   Ik zie dat je waypoint gebruikt....  Google kan wel routes berekenen maar RouteXL kan het beter en eenvoudiger. Gewoon met ook met Lat en Lng.... en als ik die niet weet Geocode is ze wel ? haha  succes en als je vragen hebt schroom niet

**Comment by ghost** [comment]
In de developers Url van je notitie hierboven gebruik ik regelmatig language=nl   of anders....   Duitsland is al helemaal een ramp met umlauts !!!    Het gaat dus niet om Javascript of instellingen daarin.... ik bedoel puur requesten naar Google.... en dan het vullen van je stops !  Of dat goed weet ik niet maar geen markers is geen input !

**Comment by vvim** [comment]
zie https://www.routexl.nl/blog/api/?lang=en

**Comment by ghost** [comment]
Ik ken RouteXL maar al te goed !  Tot 10 points...daarna betalen maar dan ook onbeperkt routes maken...  Je wil niet weten hoeveel ik er dagelijks maak !!!

**Comment by vvim** [comment]
created https://stackoverflow.com/questions/47574867/google-maps-api-no-longer-shows-routes-or-markers

check bug tracker https://issuetracker.google.com/savedsearches/558438

**Comment by ghost** [comment]
Beste Wim, ik denk dat je het kunt vinden in de verschillen tussen de karakter encoding Linux (UTF8) en Windows (UTF-16), even checken of je op 22 november 2017 een Windows Update hebt gehad !  Of is om de eoa reden je Character set gewijzigd....   Ik ben bijna 100% dat het daar in zit...    en anders check de html class in QWebview en zie wat daar wordt omgedraaid ??  http://doc.qt.io/qt-4.8/qwebview.html

**Comment by vvim** [comment]
Bedankt voor de tips! Ik heb nog geen tijd kunnen maken om het te testen maar hoop dit snel te doen!

Nog een paar notities voor mezelf:

- https://www.lookout.net/2012/02/testing-charset-encoding-support-in-web.html
- http://www.lookout.net/test/charsets/iana-charset-support/
- https://superuser.com/questions/1160003/how-do-i-change-the-character-encoding-for-a-webpage-in-chrome
- https://www.w3.org/International/questions/qa-validator-charset-check
- https://www.w3.org/International/questions/qa-validator-charset-check
- https://www.whatsmybrowser.org/

- https://www.whatismybrowser.com/

**Comment by vvim** [comment]
there was a new version put out on 21st November 2017, version 3.31 https://developers.google.com/maps/documentation/javascript/releases . The next day, users complained about the program no longer functioning correctly

Release Notes of Google Maps API 3.31 https://developers.google.com/maps/documentation/javascript/releases

More information on API versioning: https://developers.google.com/maps/documentation/javascript/versions

How to access API version: https://stackoverflow.com/questions/2310705/how-can-i-access-the-version-number-of-the-google-maps-api-in-javascript

Branch created for changing to older version of the API on Windows-platforms: https://github.com/vvim/routetool/tree/google-maps-version-issue-49

**Comment by ghost** [comment]
If you do not explicitly specify a version, you will receive the experimental version by default if you are on the standard plan (this includes customers who do not provide a key).

en daar ga je dan.... v3

**Comment by vvim** [comment]
current patch available: c30534bbe398eaebbd861ffd9b75be0746d12f57 works on test computer (Windows 10, Qt 4.8.6)

Routetool now asks Google Maps to specifically use version 3.29 of the API . Question: how long will Google Maps provide this API-version.

Research is still needed to check if we can make routetool compatible with the newest version (3.31) of the Google Maps API. See suggestions of MHermsen above.
